import { CommonAggregationOptions } from '.';
import { ScriptObject } from '../common';

/**
 * A single-value metrics aggregation that computes the average of numeric values that are extracted
 * from the aggregated documents. These values can be extracted either from specific numeric fields
 * in the documents, or be generated by a provided script.
 * 
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html
 */
export interface AvgAggregation {
    avg: AvgAggregationOptions;
}

export interface BasicAvgAggregationOptions {
    field?: string;
    /**
     * The missing parameter defines how documents that are missing a value should be treated.
     * By default they will be ignored but it is also possible to treat them as if they had a value.
     */
    missing?: number;
    script?: ScriptObject;
}

export interface AvgAggregationOptions extends BasicAvgAggregationOptions, CommonAggregationOptions { }