import { CommonAggregationOptions } from '.';
import { ScriptObject } from '../common';

/**
 * A `boxplot` metrics aggregation that computes boxplot of numeric values extracted from the aggregated documents.
 * These values can be generated by a provided script or extracted from specific numeric or histogram fields
 * in the documents.
 * 
 * The `boxplot` aggregation returns essential information for making a box plot: minimum, maximum median,
 * first quartile (25th percentile) and third quartile (75th percentile) values.
 * 
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-boxplot-aggregation.html
 */
export interface BoxplotAggregation {
    boxplot: BoxplotAggregationOptions;
}

export interface BoxplotAggregationOptions extends CommonAggregationOptions {
    field?: string;
    script?: ScriptObject;
    compression?: number;
    /**
     * The missing parameter defines how documents that are missing a value should be treated.
     * By default they will be ignored but it is also possible to treat them as if they had a value.
     */
    missing?: number;
}