import { CommonAggregationOptions } from '.';
import { ScriptObject } from '../common';

/**
 * A `single-value` metrics aggregation that calculates an approximate count of distinct values.
 * Values can be extracted either from specific fields in the document or generated by a script.
 * 
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html
 */
export interface CardinalityAggregation {
    cardinality: CardinalityAggregationOptions;
}

export interface CardinalityAggregationOptions extends CommonAggregationOptions {
    field?: string;
    /**
     * The `precision_threshold` options allows to trade memory for accuracy, and defines a unique count below
     * which counts are expected to be close to accurate. Above this value, counts might become a bit more fuzzy.
     * The maximum supported value is 40000, thresholds above this number will have the same effect
     * as a threshold of 40000. The default value is `3000`.
     */
    precision_threshold?: number;
    /**
     * The missing parameter defines how documents that are missing a value should be treated.
     * By default they will be ignored but it is also possible to treat them as if they had a value.
     */
    missing?: number | 'N/A';
    script?: ScriptObject;
}