import { CommonAggregationOptions } from '.';
import { BasicStatsAggregationOptions } from './stats';

/**
 * A `multi-value` metrics aggregation that computes stats over numeric values extracted from the aggregated documents.
 * These values can be extracted either from specific numeric fields in the documents,
 * or be generated by a provided script.
 * 
 * The `extended_stats` aggregations is an extended version of the `stats` aggregation, where additional metrics are
 * added such as `sum_of_squares`, `variance`, `std_deviation` and `std_deviation_bounds`.
 * 
 * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-extendedstats-aggregation.html
 */
export interface ExtendedStatsAggregation {
    extended_stats: ExtendedStatsAggregationOptions;
}

export interface ExtendedStatsAggregationOptions extends BasicStatsAggregationOptions, CommonAggregationOptions {
    /**
     * `sigma` controls how many standard deviations +/- from the mean should be displayed.
     * `sigma` can be any non-negative double, meaning you can request non-integer values such as `1.5`.
     * A value of `0` is valid, but will simply return the average for both `upper` and `lower` bounds.
     * 
     * The`upper` and `lower` bounds are calculated as population metrics so they are always the same
     * as `upper_population` and `lower_population` respectively.
     */
    sigma: number;
}